= Red Hat Single Sign-On integration with Red Hat Data Grid
Álvaro López Medina <alopezme@redhat.com>
v1.0, 2021-12
// Create TOC wherever needed
:toc: macro
:sectanchors:
:sectnumlevels: 2
:sectnums: 
:source-highlighter: pygments
:imagesdir: images
// Start: Enable admonition icons
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:icons: font
endif::[]
// End: Enable admonition icons


// Create the Table of contents here
toc::[]

== Introduction

This project describes how to deploy a Red Hat Single Sign-On (RH-SSO) instance on Openshift that uses Red Hat Data Grid (RHDG) for the replication of data between the data centers.


== Red Hat Single Sign-On

Red Hat Single Sign-On is an integrated sign-on solution available as a Red Hat JBoss Middleware for OpenShift containerized image. The Red Hat Single Sign-On for OpenShift image provides an authentication server for users to centrally log in, log out, register, and manage user accounts for web applications, mobile applications, and RESTful web services.






== Installing RH-SSO with the operator


[NOTE]
====
https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.5/html-single/server_installation_and_configuration_guide/index#operator[Link to the official documentation].
====

A Kubernetes Operator based on the Operator SDK for installing and managing Red Hat Single Sign-On.

Install the RH-SSO operator using the template provided in this git repository:

[source, bash]
----
oc process -f rhsso-operator/rhsso-01-operator.yaml | oc apply -f -
----

This operator installs five different CRDs that you can use to customize your RH-SSO installation:

* *Keycloak*: Represents a Red Hat Single Sign-On Instance.
* *KeycloakRealm*: Represents a Red Hat Single Sign-On Realm.
* *KeycloakBackup*: Represents a Red Hat Single Sign-On Backup.
* *KeycloakClient*: Represents a Red Hat Single Sign-On Client.
* *KeycloakUser*: Represents a Red Hat Single Sign-On User.

=== Keycloak instance



=== Keycloak Realm



=== Keycloak Backup



=== Keycloak Client



=== Keycloak User





== Installing RH-SSO using OCP templates

[NOTE]
====
https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.5/html-single/red_hat_single_sign-on_for_openshift_on_openjdk/index[Link to the official documentation].
====







== Installing RHDG using the operator

This is covered in another repository, so please, go to https://github.com/alvarolop/rhdg8-server#deploying-rhdg-on-ocp-using-the-operator[this repository] and install it manually or using the `auto-install.sh` script.








== Configuring Cross-Datacenter Replication Mode in RH-SSO

[NOTE]
====
https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.5/html-single/server_installation_and_configuration_guide/index#crossdc-mode[Link to the official documentation].
====






:sectnums!:

== Annex: Additional documentation

* Varsha Sharma's https://developers.redhat.com/blog/2021/04/23/integrate-red-hat-data-grid-and-red-hats-single-sign-on-technology-on-red-hat-openshift[blog post] about this integration 

* https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.5[RHSSO documentation].
* https://www.keycloak.org/[Keycloak documentation].
* https://github.com/keycloak/keycloak-operator[Keycloak operator documentation].
* https://access.redhat.com/documentation/en-us/red_hat_data_grid/8.2[RHDG documentation].
* https://access.redhat.com/solutions/3296901[RH-SSO Release History].