apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rhsso-operator
  annotations:
    description: Template to deploy a RHSSO operator on OCP.
    tags: keycloak,rhsso,operator
    iconClass: icon-sso
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    name: ${OPERATOR_NAMESPACE}
    annotations:
      openshift.io/description: "This project contains all the resources related to the operator of Red Hat Single Sign-On"
      openshift.io/display-name: "RH Single Sign-On - Operator"
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    name: ${CLUSTER_NAMESPACE}
    annotations:
      openshift.io/description: "This project contains all the clusters deployed of Red Hat Single Sign-On"
      openshift.io/display-name: "RH Single Sign-On"
- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    name: rhsso
    namespace: ${OPERATOR_NAMESPACE}
  spec:
    targetNamespaces:
      - ${CLUSTER_NAMESPACE}
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: datagrid-operator
    namespace: ${OPERATOR_NAMESPACE}
  spec:
    channel: alpha
    installPlanApproval: Automatic
    name: rhsso-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: rhsso-operator.7.5.1-opr-001
parameters:
- name: OPERATOR_NAMESPACE
  description: "The project where the RH-SSO operator will be installed."
  required: false
  value: "rhsso-operator"
- name: CLUSTER_NAMESPACE
  description: "The project where the RH-SSO cluster will be installed."
  required: false
  value: "rhsso"